apiVersion: v1
kind: Service
metadata:
  name: login-web
  labels:
    app: login-web
spec:
  type: LoadBalancer
  selector:
    app: login-web
  ports:
    - name: http
      port: 80
      targetPort: 80
